package com.example.smsapp.utils


const val NOTIFICATION_CHANNEL_ID_PRIMARY="SMS_PRIMARY"

const val NOTIFICATION_CHANNEL_NAME_PRIMARY="Primary sms"

const val NOTIFICATION_CHANNEL_ID_NORMAL="SMS_NORMAL"

const val NOTIFICATION_CHANNEL_NAME_NORMAL="Normal sms"


const val NOTIFICATION_CHANNEL_ID_NORMAL_HIGH="SMS_HIGH"

const val NOTIFICATION_CHANNEL_NAME_NORMAL_HIGH="High Priority sms"

const val LOCAL_SMS_NOTIFIER="LOCAL_SMS_NOTIFIER"

